title: "System Signal"
description: "Karthik – product strategist, systems thinker, builder of trust-first tech"
baseurl: ""
url: "https://systemsignal.dev"
theme: null

markdown: kramdown
permalink: pretty

# Optional social
email: karthik@systemsignal.dev
github_username: elkarto91
linkedin_username: karthik-m-portfolio
twitter_username: chaingopher
collections:
  projects:
    output: true
    permalink: /projects/:name/
